const archiver = require('archiver');
const path = require('path');
const fs = require('fs');

const LICENSE_TEXT = `This game was generated by GalBundler.
Repository: https://github.com/fcanlnony/GalBundler

All rights to the images and story content belong to their respective owners.
The generator code is provided under the terms of the GalBundler project license.
`;

const README_TEXT = `# Generated GalGame

This game was generated by [GalBundler](https://github.com/fcanlnony/GalBundler).

## How to Run

1. Make sure you have [Node.js](https://nodejs.org/) installed.
2. Extract this ZIP archive.
3. Install dependencies:
   \`\`\`
   npm install
   \`\`\`
4. Start the game:
   \`\`\`
   node src/server.js
   \`\`\`
5. Open your browser and navigate to the URL shown in the terminal.
`;

/**
 * Generate a GalGame ZIP archive.
 *
 * @param {Object} options
 * @param {string} options.outputPath - Where to write the ZIP file.
 * @param {string} options.title - Game title.
 * @param {Array<{name: string, data: Buffer, group?: string}>} options.images - Images to include.
 * @param {string} options.mainHtml - HTML content for main.html.
 * @param {Object<string, string>} [options.srcFiles] - Additional src/ files (relative path -> content).
 * @returns {Promise<string>} Path to the generated ZIP.
 */
function generate(options) {
  const { outputPath, title, images = [], scenes = [], mainHtml, srcFiles = {} } = options;

  return new Promise((resolve, reject) => {
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const output = fs.createWriteStream(outputPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => resolve(outputPath));
    archive.on('error', (err) => reject(err));

    archive.pipe(output);

    // LICENSE
    archive.append(LICENSE_TEXT, { name: 'LICENSE' });

    // README.md
    archive.append(README_TEXT, { name: 'README.md' });

    // main.html
    archive.append(mainHtml || getDefaultMainHtml(title, scenes, images), { name: 'main.html' });

    // src/ files
    // Always include a minimal server.js for the generated game
    if (!srcFiles['server.js']) {
      srcFiles['server.js'] = getDefaultServerJs();
    }
    if (!srcFiles['package.json']) {
      srcFiles['package.json'] = getDefaultPackageJson(title);
    }

    for (const [filePath, content] of Object.entries(srcFiles)) {
      if (filePath === 'package.json') {
        archive.append(content, { name: filePath });
      } else {
        archive.append(content, { name: `src/${filePath}` });
      }
    }

    // pictures/
    for (const img of images) {
      const group = img.group || 'default';
      archive.append(img.data, { name: `pictures/${group}/${img.name}` });
    }

    // Ensure pictures/default/ exists even if no images
    if (images.length === 0) {
      archive.append('', { name: 'pictures/default/.gitkeep' });
    }

    archive.finalize();
  });
}

function getDefaultMainHtml(title = 'GalGame', scenes = [], images = []) {
  if (scenes.length === 0) {
    return fs.readFileSync(path.join(__dirname, '..', 'frontend', 'main.html'), 'utf-8')
      .replace(/{{TITLE}}/g, title);
  }

  // Build a playable GalGame HTML with embedded scene data
  const scenesJson = JSON.stringify(scenes.map(s => ({
    bg: s.bg || '',
    character: s.character || '',
    speaker: s.speaker || '',
    text: s.text || '',
  })));

  // Map image names to their picture paths in the ZIP
  const imageGroup = (images[0] && images[0].group) || 'default';
  const imageMapJson = JSON.stringify(
    images.reduce((acc, img) => {
      acc[img.name] = `pictures/${imageGroup}/${img.name}`;
      return acc;
    }, {})
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #000; font-family: 'Segoe UI', Roboto, sans-serif; overflow: hidden; }
    .game-container { width: 100vw; height: 100vh; position: relative; cursor: pointer; user-select: none; }
    .game-bg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; }
    .game-character { position: absolute; bottom: 20%; left: 50%; transform: translateX(-50%); max-height: 80%; max-width: 60%; object-fit: contain; }
    .game-dialog { position: absolute; bottom: 0; left: 0; right: 0; background: linear-gradient(transparent, rgba(0,0,0,0.85)); padding: 32px 24px 20px; color: #fff; }
    .game-speaker { font-size: 16px; font-weight: 600; color: #D0BCFF; margin-bottom: 6px; }
    .game-text { font-size: 18px; line-height: 1.6; }
    .game-controls { position: absolute; top: 16px; right: 16px; display: flex; gap: 8px; }
    .game-controls button { width: 40px; height: 40px; border-radius: 50%; border: none; background: rgba(255,255,255,0.15); color: #fff; cursor: pointer; font-size: 18px; backdrop-filter: blur(4px); }
    .game-controls button:hover { background: rgba(255,255,255,0.3); }
    .game-counter { position: absolute; top: 20px; left: 20px; color: rgba(255,255,255,0.5); font-size: 14px; }
  </style>
</head>
<body>
  <div class="game-container" id="game">
    <div class="game-counter" id="counter"></div>
    <div class="game-controls">
      <button id="prevBtn" title="Previous">&#9664;</button>
      <button id="nextBtn" title="Next">&#9654;</button>
    </div>
  </div>
  <script>
    const scenes = ${scenesJson};
    const imageMap = ${imageMapJson};
    let currentIndex = 0;

    function render() {
      const game = document.getElementById('game');
      game.querySelectorAll('.game-bg, .game-character, .game-dialog').forEach(el => el.remove());
      if (scenes.length === 0) return;
      const scene = scenes[currentIndex];
      document.getElementById('counter').textContent = (currentIndex + 1) + ' / ' + scenes.length;
      if (scene.bg && imageMap[scene.bg]) {
        const img = document.createElement('img');
        img.className = 'game-bg';
        img.src = imageMap[scene.bg];
        game.appendChild(img);
      }
      if (scene.character && imageMap[scene.character]) {
        const img = document.createElement('img');
        img.className = 'game-character';
        img.src = imageMap[scene.character];
        game.appendChild(img);
      }
      if (scene.speaker || scene.text) {
        const dialog = document.createElement('div');
        dialog.className = 'game-dialog';
        if (scene.speaker) { const s = document.createElement('div'); s.className = 'game-speaker'; s.textContent = scene.speaker; dialog.appendChild(s); }
        if (scene.text) { const t = document.createElement('div'); t.className = 'game-text'; t.textContent = scene.text; dialog.appendChild(t); }
        game.appendChild(dialog);
      }
    }

    document.getElementById('prevBtn').addEventListener('click', (e) => { e.stopPropagation(); currentIndex = (currentIndex - 1 + scenes.length) % scenes.length; render(); });
    document.getElementById('nextBtn').addEventListener('click', (e) => { e.stopPropagation(); currentIndex = (currentIndex + 1) % scenes.length; render(); });
    document.getElementById('game').addEventListener('click', () => { currentIndex = (currentIndex + 1) % scenes.length; render(); });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowLeft') { currentIndex = (currentIndex - 1 + scenes.length) % scenes.length; render(); }
      if (e.key === 'ArrowRight' || e.key === ' ') { currentIndex = (currentIndex + 1) % scenes.length; render(); }
    });
    render();
  </script>
</body>
</html>`;
}

function getDefaultServerJs() {
  return `const express = require('express');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.static(path.join(__dirname, '..')));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'main.html'));
});

app.listen(PORT, () => {
  console.log('Game running at http://localhost:' + PORT);
});
`;
}

function getDefaultPackageJson(title = 'galgame') {
  return JSON.stringify({
    name: title.toLowerCase().replace(/[^a-z0-9]/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: { start: 'node src/server.js' },
    dependencies: { express: '^5.2.1' }
  }, null, 2);
}

module.exports = { generate };
